### ISSUE TITLE
cannot import name 'hephaestus_bindings' from 'helpers.hephaestus'

### ISSUE THREAD

**Issue by nghialtVTCE** [michaildoukas/headGAN#1]
Hi, thanks to the great project

When I run the script: python reenact.py --reference_path <reference_path> --driving_path <driving_path>

it returns:

![image](https://github.com/michaildoukas/headGAN/assets/111347492/3cdf676c-b521-4a23-8235-3a373d3ec84e)

Maybe I have a mistake when I try to install some packages because your repo has not requirements.txt

May you help me to fix it? Thank you very much

**Comment by michaildoukas** [comment]
Hi,

Instead of a requirements.txt, we provide is a .yml file. Before running any script, please create and activate the conda environment with:

`conda env create -f env.yml`
`conda activate headGAN`

Note: Make sure to pull the latest changes, there was an issue with the .yml file in the initial commit, which should be fixed now.

**Comment by neeek2303** [comment]
Hi @michaildoukas I've installed env with conda but have a similar problem.
